### PR TITLE
docs(ui-options): function based examples are added to Options

### PR DESCRIPTION
**Pull request by Kadirsaglm**

### CODE REVIEW

**Comment by Kadirsaglm** [comment]
Is there anything needs to be done on my side about the failure of deploy preview?

**Comment by Kadirsaglm** [comment]
Is there anything needs to be done on my side about the failure of deploy preview?

**Comment by matyasf** [comment]
> Is there anything needs to be done on my side about the failure of deploy preview?

Nope, its failing because of security restrictions, this is normal

**Review by ToMESSKa — APPROVED** [review]

**Comment by Kadirsaglm** [comment]
> > Is there anything needs to be done on my side about the failure of deploy preview?
> 
> 
> 
> Nope, its failing because of security restrictions, this is normal

Are you planning to merge this PR? I can't merge because of the failing check

**Comment by matyasf** [comment]
> Are you planning to merge this PR? I can't merge because of the failing check

Only repo maintainers are able to merge pull requests. When its approved by us we will merge it

**Comment by Kadirsaglm** [comment]
> > Are you planning to merge this PR? I can't merge because of the failing check
> 
> Only repo maintainers are able to merge pull requests. When its approved by us we will merge it

Thanks for the clarification!

**Pull request merged**
