### PR TITLE
INSTUI-3103 - resolve mocha type errors in tests

### PR DESCRIPTION
**Pull request by ke1k0**
Closes: INSTUI-3103

### CODE REVIEW

**Review by Brailor — COMMENTED** [review]
I don't think we have to add `@types/mocha` to every package since common dependencies are hoisted to the root `node_modules` by lerna. Thus I would add the `@types/mocha` devDependency to the package that actually has a dependency on mocha (`ui-scripts`), or put in the root package.json.

**Review by matyasf — APPROVED** [review]

**Comment by matyasf** [comment]
> Thus I would add the @types/mocha devDependency to the package that actually has a dependency on mocha (ui-scripts), or put in the root package.json.

But if we put them into e.g. the root JSON wont it throw errors for people who use just one package from us?

**Comment by Brailor** [comment]
> > Thus I would add the @types/mocha devDependency to the package that actually has a dependency on mocha (ui-scripts), or put in the root package.json.
> 
> But if we put them into e.g. the root JSON wont it throw errors for people who use just one package from us?

I don't think so, because they can't run our tests since they are not published to npm.

**Comment by ke1k0** [comment]
> > > Thus I would add the @types/mocha devDependency to the package that actually has a dependency on mocha (ui-scripts), or put in the root package.json.
> > 
> > 
> > But if we put them into e.g. the root JSON wont it throw errors for people who use just one package from us?
> 
> I don't think so, because they can't run our tests since they are not published to npm.

Fixed, thanks :)

**Review by Brailor — APPROVED** [review]

**Pull request merged**
