### PR TITLE
Replace shortid with nanoid

### PR DESCRIPTION
**Pull request by killbillsbor**
Hi!

Possible way to complete issue #10. Unfortunately, not all the test are working on my computer :(

Please review and let me know if might be improved.

Thanks!

### CODE REVIEW

**Comment by junyper** [comment]
Looks like spam

**Comment by killbillsbor** [comment]
Hey, @junyper! Can I help you with this PR? Thanks!

**Comment by ai** [comment]
@personable do you need to update PR? You use deprecated, slow and unsafe ID generator ;)

**Comment by arlodesign** [comment]
We'll investigate if this library will work for us. Thanks for bringing it to our attention. In the meantime, we're going to close this.

**Comment by ai** [comment]
@arlodesign feel free to ask any question.

Also, note that the maintainers of `shortid` supported `nanoid`. Do you really need investigation if `shortid` maintainers tell you to switch as soon as possible because of distribution problems and bigger size? ;)

**Comment by arlodesign** [comment]
@ai https://github.com/instructure/instructure-ui/commit/b779d7d4be50357184f337b7e94fe4b2ea356225

**Pull request closed without merging**
