### PR TITLE
test(ui-billboard): migrate old Billboard tests

### PR DESCRIPTION
**Pull request by git-nandor**

### CODE REVIEW

**Review by balzss — CHANGES_REQUESTED** [review]
let's also remove the old tests or at least skip them

**Comment by matyasf** [comment]
agree, lets delete them, we dont want duplicate code

**Review by balzss — CHANGES_REQUESTED** [review]
please run `npm install` and commit the new package-lock as well

**Review by HerrTopi — APPROVED** [review]

**Review by balzss — APPROVED** [review]
nice work

**Pull request merged**
