### PR TITLE
chore: disable webpack dev server client overlay

### PR DESCRIPTION
**Pull request by NamNguyenInstructure**

### CODE REVIEW

**Review by matyasf — APPROVED** [review]

**Review by HerrTopi — COMMENTED** [review]
Are you sure this is the right approach? I checked the history of this file, and we never had this line here, nevertheless, it was working correctly.
Won't we just mask a problem this way?

**Comment by matyasf** [comment]
> Are you sure this is the right approach? I checked the history of this file, and we never had this line here, nevertheless, it was working correctly. Won't we just mask a problem this way?

It could be because I've updated some Webpack dependencies

**Comment by matyasf** [comment]
> Are you sure this is the right approach? I checked the history of this file, and we never had this line here, nevertheless, it was working correctly. Won't we just mask a problem this way?

It could be because I've updated some Webpack dependencies

**Comment by matyasf** [comment]
> Are you sure this is the right approach? I checked the history of this file, and we never had this line here, nevertheless, it was working correctly. Won't we just mask a problem this way?

It could be because I've updated some Webpack dependencies

**Comment by matyasf** [comment]
> Are you sure this is the right approach? I checked the history of this file, and we never had this line here, nevertheless, it was working correctly. Won't we just mask a problem this way?

It could be because I've updated some Webpack dependencies

**Comment by matyasf** [comment]
> Are you sure this is the right approach? I checked the history of this file, and we never had this line here, nevertheless, it was working correctly. Won't we just mask a problem this way?

It could be because I've updated some Webpack dependencies

**Comment by NamNguyenInstructure** [comment]
After reviewing the old commits, I discovered that the error occurred when we update the Webpack from 5.75 to 5.78

**Comment by matyasf** [comment]
hmm so its a webpack "feature" then, perhaps "overlay" was false until now? I like the fix this way as it is now

**Review by HerrTopi — APPROVED** [review]

**Pull request merged**
