### PR TITLE
chore(release): 8.28.0

### PR DESCRIPTION
**Pull request by Brailor**

### CODE REVIEW

**Review by matyasf — CHANGES_REQUESTED** [review]
Cna you please mention in the changelog that `Element` needs to be stubbed for SSR and Jest? https://github.com/instructure/instructure-ui/pull/1088

**Comment by Brailor** [comment]
> Cna you please mention in the changelog that `Element` needs to be stubbed for SSR and Jest? #1088

Should be fixed.

**Review by ke1k0 — APPROVED** [review]
I liked it more when SSR and Jest was mentioned, I even said they should be written in bold, but otherwise approved :)

**Review by matyasf — APPROVED** [review]

**Comment by Brailor** [comment]
> I liked it more when SSR and Jest was mentioned, I even said they should be written in bold, but otherwise approved :)

Sorry it was a misunderstanding from my part, fixed.

**Pull request merged**
