### PR TITLE
feat(ui-tree-browser): allow tree browser to render before, after nodes

### PR DESCRIPTION
**Pull request by prenner**
closes OUT-4216

test-plan:
- run docs app locally
- ensure before/afterCollection props work as expected
- test the above with VO/NVDA

### CODE REVIEW

**Comment by prenner** [comment]
the first commit had a passing build, but the second failed with 

>✖ Missing project token (chromatic)

not entirely sure what that is but that commit was a one line change so let me know if there's anything more needed there

**Comment by matyasf** [comment]
Thank you for your pull request! We will check it out soon and merge it if it looks OK

**Review by Brailor — APPROVED** [review]
Thanks for the PR!
Looks good to me.

**Comment by prenner** [comment]
Thanks for the review!

**Comment by matyasf** [comment]
Hi!
one a11y issue: I don't seem to be able to click the button inside a node via keyboard navigation

**Comment by prenner** [comment]
> Hi!
> one a11y issue: I don't seem to be able to click the button inside a node via keyboard navigation

When I was working on tests, I was specifically defining the onClick event for the button as a <TreeNode> prop, rather than as part of whatever children I was rendering. This was mostly due to the weirdness of how tree browser handles focus (from what I can tell) but you may have some other suggestions/improvements on how to handle that.

**Review by matyasf — APPROVED** [review]

**Pull request merged**
