### PR TITLE
fix(shared-types,ui-table): fix color contrast for table sorting icons

### PR DESCRIPTION
**Pull request by HerrTopi**
Closes: INSTUI-4238

### CODE REVIEW

**Review by balzss — APPROVED** [review]
looks better, works better

**Comment by balzss** [comment]
note: it'd be nice if chromatic could catch these type of changes...

**Review by matyasf — APPROVED** [review]

**Comment by HerrTopi** [comment]
Chromatic would probably catch this if we had examples for this exact config, which we don't

**Comment by HerrTopi** [comment]
Currently blocked by design. Final color decision is coming soon

**Pull request merged**
